# Generated by Django 3.1.5 on 2021-01-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210127_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='image',
            field=models.TextField(blank=True, default='products/empty.png', max_length=255, null=True, verbose_name='Imagen del Producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/empty.png', max_length=255, null=True, upload_to='products/', verbose_name='Imagen del Producto'),
        ),
    ]
